### PR TITLE
Added clarity to syno/qnap wg0

### PR DESCRIPTION
**Pull request by andytheholy**
Added clarification on `Additional_IPs` for wg0 file in Syno/QNAP section

### CODE REVIEW

**Comment by mrhotio** [comment]
Don’t remove the dot.

**Comment by andytheholy** [comment]
Dot returned I think.

**Comment by mrhotio** [comment]
Terribly sorry, but now we are here can you also fix the A of allewedips, no idea how the accent ended up there…. I’ll upgrade your role on discord :-)

**Comment by andytheholy** [comment]
Lol fixed. I’m on my iPhone so have to long-press for the back-tick - maybe it carried over to the A?

**Comment by andytheholy** [comment]
…and sorry for the goofy PR title!

**Comment by mrhotio** [comment]
Nah, I messed up the A in the past…

**Pull request merged**
