### PR TITLE
Update wireguard.md with some clarity on wg0 for syno/qnap

### PR DESCRIPTION
**Pull request by andytheholy**
…and added a link to Trash’s TorGuard instructions

### CODE REVIEW

**Comment by mrhotio** [comment]
We are not going mid instructions going to say “go look here”, nor are going to say in the non syno section to be extra careful for when you’ve got a syno.

**Comment by andytheholy** [comment]
Fair point on the link to Trash, but the 2nd change is squarely in the Synology/QNAP section for editing the wg0

**Comment by mrhotio** [comment]
My bad, just woke up from a nap… feel free to create a new PR for just that… Ideally the torguard instructions should have their own page on the site under VPN section

**Comment by andytheholy** [comment]
No sweat, I’m about to take a nap myself. lmk if you want me to throw that link to Trash somewhere. Didn’t you write those?

**Pull request closed without merging**
