### PR TITLE
update doplarr configuration and description

### PR DESCRIPTION
**Pull request by kiranshila**
The inclusion of the quality/language profiles change the runtime behavior and stops doplarr from prompting for those options. I'm not sure how that is to be handled for the hotio stuff so please revise as necessary.

### CODE REVIEW

**Comment by kiranshila** [comment]
I'm also not sure where the unraid templates are made, I assume there are ways to distinguish optional settings in their UI.

**Comment by mrhotio** [comment]
Now that you are messing around with the env vars, maybe this is a good time to also add a DOPLARR__ prefix?

**Comment by kiranshila** [comment]
Oh to partial seasons and log level? Yeah I could do that for consistency's sake

**Comment by kiranshila** [comment]
Oh good point. I'd have to look to see if there'd be a conflict. Thanks!

**Pull request merged**
